export const KEYPRESS_RECEIVED = 'KEYPRESS_RECEIVED';
export const USER_LOGGED_ON = 'USER_LOGGED_ON';
export const REGISTER_NEW_USER = 'REGISTER_NEW_USER';
export const SEND_KEY_PRESS = 'SEND_KEY_PRESS';
export const SOCKET_CLOSED = 'SOCKET_CLOSED';
export const USER_LOGGED_OFF = 'USER_LOGGED_OFF';
export const LIST_USERS = 'LIST_USERS';